### PR TITLE
bug fix: api ransim watchues crash

### PR DESCRIPTION
**Pull request by joshuazhu78**

### CODE REVIEW

**Review by adibrastegarnia — APPROVED** [review]
@woojoong88  Please verify this.

**Comment by woojoong88** [comment]
Is it tested? working? @joshuazhu78 
I am thinking that there was a reason why we used to watch `route` event not `ue` event.
If @joshuazhu78 can say it is working on his setup, I will give +1.

**Comment by joshuazhu78** [comment]
Sure it is working. @woojoong88

**Review by woojoong88 — APPROVED** [review]

**Comment by woojoong88** [comment]
Do you want me to merge it? @joshuazhu78

**Comment by joshuazhu78** [comment]
Sure. Please. @woojoong88

**Pull request merged**
