### PR TITLE
Enable some feature to support NS xApp

### PR DESCRIPTION
**Pull request by Liu-Weijie**

### CODE REVIEW

**Comment by Liu-Weijie** [comment]
> Can one of the admins verify this patch?

Sure

**Review by woojoong88 — COMMENTED** [review]
Can we move cell.csv file to Helm chart so that we can dynamically change the csv file?

**Comment by Liu-Weijie** [comment]
> Can we move cell.csv file to Helm chart so that we can dynamically change the csv file?

Sure, should I create a PR in sdran-helm-charts?

If I understand correctly, I need to put cell.csv in sdran-helm-charts/ran-simulator/files and modify the command in deployment.yaml, right?

**Comment by woojoong88** [comment]
> > Can we move cell.csv file to Helm chart so that we can dynamically change the csv file?
> 
> Sure, should I create a PR in sdran-helm-charts?
> 
> If I understand correctly, I need to put cell.csv in sdran-helm-charts/ran-simulator/files and modify the command in deployment.yaml, right?

Yes correct. So, those are the potential steps:
1. Add csv file into sdran-helm-charts/ran-simulator/files
2. Import the csv file as a `ConfigMap`
3. Add `ConfigMap` to `Deployment` so that RAN-Simulator K8s POD can use it.

Let me know once you created a PR on sdran-helm-charts.

And please don't forget the conflict resolution described below :)

**Comment by Liu-Weijie** [comment]
Hi Woojoong, I have finished putting file in configmap and let ran-simulator work normally. But I found the the size of configmap is limited, I can't put all data in configmap. I want to ask if there is a good enough solution to this issue, because we don't want to reduce the data size

**Comment by woojoong88** [comment]
> 

Hmm.. ok then, let's put that into the RAN-Simulator. I will figure that out.

**Comment by Liu-Weijie** [comment]
> > 
> 
> Hmm.. ok then, let's put that into the RAN-Simulator. I will figure that out.

Sure, thanks.

**Comment by Liu-Weijie** [comment]
As for conflicts, should I rebase onosproject:master or only resolve conflicts

**Comment by woojoong88** [comment]
Since CI did not work, I forced to merge this PR.

**Pull request merged**
