### PR TITLE
Added in writing out HO metrics to Influx DB

### PR DESCRIPTION
**Pull request by SeanCondon**
We can decide whether was want to write to Influx or Prometheus

I've run this and it gives me results like below

@shadansari can you check the logic - I'm storing nano seconds here but 
by the size of the values I think it's giving me the time between one Handover and the next?
```
> select * from hometrics
name: hometrics
time                ue   value
----                --   -----
1582752180362138167 0002 19867311202
1582752191734577056 0003 8495671580
1582752203738104212 0003 6004582628
1582752212740280125 0003 30011140674
1582752222742724243 0002 5005277715
1582752230745235400 0002 6007639481
1582752242748850121 0002 28013498195
1582752245749589281 0003 6005106746
1582752256752712680 0003 14015883288
1582752273756924345 0002 6003596911
1582752277757665966 0003 8013503360
1582752282758821480 0002 3003231959
1582752286759982643 0002 7003387807
1582752297762598905 0002 3004596287
1582752324462654227 0003 71819915744
1582752324663216226 0002 71618597969
1582752336191261981 0001 85018323743
1582752397203661381 0002 5002690943
1582752397203666076 0003 8003288407
1582752407205527437 0002 12003670754
1582752408205733786 0003 8002725060
1582752443211599405 0003 1517689
1582752444211747122 0002 1728930
1582752444211751529 0003 9003814717
1582752446212163177 0002 2001838110
1582752451212834702 0001 1517060
1582752451212840367 0002 8008786688
1582752455213530378 0001 2001981965
1582752457213867306 0003 20015395971
1582752459214287198 0001 8003704608
1582752460214486366 0002 1961985
1582752463215043493 0002 11004693078
1582752476217751746 0002 1001791690
1582752481218840706 0002 2002314485

```

### CODE REVIEW

**Comment by tomikazi** [comment]
> I am seeing similar numbers (your numbers avg 14 sec, my run was 19 sec). I am looking at the logic for latency calculation.

1582752297762598912... that's not 15 seconds... that's 1582752297.7625989914 seconds.

**Comment by shadansari** [comment]
@tomikazi  - I think the first column (time) is the timestamp when the value was added into Influxdb. I am assuming that third column (value) is the latency in nanoseconds.

**Comment by tomikazi** [comment]
Yeah… I realized that as soon as I hit send so I deleted the comment. My mind was just being the first column as the latency; doh! :)

Thomas

**Comment by SeanCondon** [comment]
Using prometheus instead

**Pull request closed without merging**
